### ISSUE TITLE
circular_check_box causing error when building apk

### ISSUE THREAD

**Issue by Adem68** [biplazma/mobile#1]
https://pub.dev/packages/circular_check_box

We need to write custom checkbox from scratch or choose another package.

**Comment by muarifer** [comment]
I think it's "android" folder is useless.

If we fork and create only "Dart package" it'll work i think.

**Comment by Adem68** [comment]
Hi @muarifer,

Firstly, thx for message.

You can see error from [here](https://github.com/biplazma/mobile/runs/637185738)

Click `Run flutter build apk`

Error is not related to android folder

**Comment by Adem68** [comment]
Problem was fixed with Flutter 1.17 migration :smiley:   
 

https://github.com/Adem68/circular_check_box
